### ISSUE TITLE
1.0.4 triggers "PHP Fatal error:  Nesting level too deep - recursive dependency?" in src/Elements/Node:91

### ISSUE THREAD

**Issue by tarantuli** [sfire-framework/sfire-dom#1]
I haven't found any easily identifiable causes yet. I can e-mail you a template file that triggers it, if you want to.

The file compiles correctly when using version 1.0.3

**Comment by sfire-framework** [comment]
Thank you for your report. Bug could be reproduced and is fixed in version 1.0.5.
